/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useMemo } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

const PruebaTex = (props) => {
  const { nodes, materials } = useGLTF("/models/C01_Tex.glb");

  const c03Texture = useTexture("./textures/C01/C01_Wall.jpg");
  // c03Texture.flipY = true;
  c03Texture.colorSpace = THREE.SRGBColorSpace;

  // c03Texture.wrapS = c03Texture.wrapT = THREE.RepeatWrapping;
  // c03Texture.repeat.set(40, 40);

  // Floor 01
  const matFloor = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: c03Texture,
      toneMapped: false,
    });
  }, [c03Texture]);

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.C01W_Wall01_Text02.geometry}
        // material={materials["brick_wall_003.001"]}
        material={matFloor}
      />
    </group>
  );
};

useGLTF.preload("/models/C01_Tex.glb");

export default PruebaTex;
