/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useMemo } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

const PruebaC03 = (props) => {
  const { nodes, materials } = useGLTF("/models/C01_Tex03.glb");

  const c03SohoTexture = useTexture("./textures/Soho_Prueba_Tex03.jpg");
  c03SohoTexture.flipY = false;
  c03SohoTexture.colorSpace = THREE.SRGBColorSpace;

  //   c03SohoTexture.wrapS = c03SohoTexture.wrapT = THREE.RepeatWrapping;
  //   c03SohoTexture.repeat.set(4, 4);

  // Floor 01
  const matSohoFloor = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: c03SohoTexture,
      toneMapped: false,
    });
  }, [c03SohoTexture]);

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.C03W_Wall001.geometry}
        // material={materials['brick_wall_003.001']}
        material={matSohoFloor}
      />
    </group>
  );
};

useGLTF.preload("/models/C01_Tex03.glb");

export default PruebaC03;
